from django.conf.urls import patterns, url
from wt import views

# for django to pick up mapping must use name 'urlpatterns'
urlpatterns = patterns( '',
    url( r'^$', views.home, name='home'),
    url( r'^graph/(?P<user_id>\d+)/', views.graph, name='user_graph'),
    url( r'^graph/', views.graph, name='graph'),
    url( r'^questions/', views.questions, name='questions'),
    url( r'^patients/', views.patient_list, name='patient_list'),
    url( r'^following/', views.following_list, name='following_list'),
    url( r'^planning/(?P<user_id>\d+)/', views.planning, name='planning'),
    url( r'^goal_summary/(?P<user_id>\d+)/', views.goal_summary, name='goal_summary'),
    url( r'^overall_summary/(?P<user_id>\d+)/', views.overall_summary, name='overall_summary'),
    url( r'^new_strategy/(?P<user_id>\d+)/', views.new_strategy, name='new_strategy'),
    url( r'^new_strategy_planning/(?P<user_id>\d+)/', views.new_strategy_planning, name='new_strategy_planning'),
    url( r'^new_strategy_selection/(?P<user_id>\d+)/', views.new_strategy_selection, name='new_strategy_selection'),
    url( r'^createpatient/', views.create_patient, name='create_patient'),
    url( r'^new_question/(?P<user_id>\d+)/', views.new_question,     name='new_question'),
    url( r'^appendix_va', views.appendix_va, name='appendix_va'),
    url( r'^appendix_vb', views.appendix_vb, name='appendix_vb'),
    url( r'^gas_step1/(?P<user_id>\d+)/', views.gas_step1, name='gas_step1'),
    url( r'^gas_goal_selection/(?P<user_id>\d+)/', views.gas_goal_selection, name='gas_goal_selection'),
    url( r'^new_strategy/(?P<user_id>\d+)/', views.new_strategy, name='new_strategy'),
	url( r'^profile/', views.profile, name='profile'),
    url( r'^add_so/', views.add_so, name='add_so'),
    url( r'^followup_goaledit/(?P<user_id>\d+)/', views.followup_goal_selection, name='followup_goal_selection'),
    url( r'^followup_goal_create/(?P<user_id>\d+)/', views.followup_goal_create, name='followup_goal_create'),
    url( r'^followup_goal_selection/(?P<user_id>\d+)/', views.followup_goaledit, name='followup_goaledit'),
    url( r'^followup_goal_planning/(?P<user_id>\d+)/', views.followup_goal_planning, name='followup_goal_planning'),
    url( r'^followup_goal_summary/(?P<user_id>\d+)/', views.followup_goal_summary, name='followup_goal_summary'),
    url( r'^followup_overall_summary/(?P<user_id>\d+)/', views.followup_overall_summary, name='followup_overall_summary'),
    url( r'^followup_strategyedit/(?P<user_id>\d+)/', views.followup_strategyedit, name='followup_strategyedit'),
    url( r'^followup_strategy_create/(?P<user_id>\d+)/', views.followup_strategy_create, name='followup_strategy_create'),
    url( r'^followup_strategy_selection/(?P<user_id>\d+)/', views.followup_strategy_selection, name='followup_strategy_selection'),
    url( r'^followup_strategy_planning/(?P<user_id>\d+)/', views.followup_strategy_planning, name='followup_strategy_planning'),
    url( r'^manage_surveys/', views.manage_surveys, name='manage_surveys'),
    url( r'^create_survey/', views.create_survey, name='create_survey'),
    url( r'^edit_survey/', views.edit_survey, name='edit_survey'),
    url( r'^survey_overview/(?P<survey_id>\d+)/', views.survey_overview, name='survey_overview'),
    url( r'^s_new_question/', views.s_new_question, name='s_new_question'),
)
